FROM centos7/base2a
MAINTAINER Wu

ENV WORKDIR=/tmp/wk

WORKDIR $WORKDIR
#################################
# Download or install packages.
#################################

RUN wget http://dl.mycat.io/1.6.5/Mycat-server-1.6.5-release-20180122220033-linux.tar.gz

#docker build --force-rm=true -t centos7/mycat1a ./
