FROM centos7/base2a
MAINTAINER Wu

ENV WORKDIR=/tmp/wk

WORKDIR $WORKDIR
#################################
# Download or install packages.
#################################

RUN wget http://www-us.apache.org/dist/hadoop/common/hadoop-2.9.1/hadoop-2.9.1.tar.gz

#docker build --force-rm=true -t centos7/hadoop1a ./
