FROM centos7/postgres1a
MAINTAINER Wu

# ENV varables.

ENV WORKDIR=/tmp/wk

WORKDIR $WORKDIR

# install pgAdmin4
RUN yum install -y pgadmin4

EXPOSE 1-65535

# docker build --force-rm=true -t centos7/postgres2a ./

